apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 023891380390.dkr.ecr.ap-northeast-1.amazonaws.com/adam/user-client
  newTag: 3355e9cd4bef1a240254643b4b8dc5fe2ad117f8
- name: 457472006214.dkr.ecr.us-west-1.amazonaws.com/guestbook
  newTag: d6cbdc0df33ef5f5dce803931e4d89031865223b
- name: frontend
  newName: guestbook
  newTag: 3fa38b9d2acb82a6e567c5935d1037a1339e4f1d
- name: guestbook
  newName: guestbook
  newTag: new
- name: mills-nick.dkr.ecr.ap-northeast-1.amazonaws.com/adam/user-client
  newTag: 5cecd28beac302200506609a4565615c4394247c
- name: mills-nick.dkr.ecr.ap-northeast-1.amazonaws.com/guestbook
  newTag: 26cf857529215c3af89cfa81e973e1c80570781b
